bugfix/calculator/third-corrections
NikitaDr-ON/CourseProject pull request #6
Opened 2024-11-28 21:02 UTC by NikitaDr-ON

Исправлены баги, добавлены интерфейсы для сервисов

2024-12-01 10:28 UTC, fancestyao requested changes

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        return (result);
В прошлый раз указывал на лишние скобки

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        return scoringServiceImpl.scoring(scoringDataDto);
В прошлый раз указывал, что лучше переменную result сделать и ее возвращать, а не дублировать вызов метода в логгере

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/LoanOfferDto.java
> +    @Schema(name = "isInsuranceEnabled", example = "true")
Неправильное имя отображаешь

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/PaymentScheduleElementDto.java
> +    private BigDecimal remainingDebt;
Неправильные имена отображаешь

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/ScoringDataDto.java
> +    private LocalDate passportIssueDate;
Passport issue date это дата выдачи паспорта, а она у тебя в примере выдается в будущем

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/CalculationServiceImpl.java
> +        int daysInMonth = 0;
Лишняя инициализация, на 55 присвоение уже есть

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/CalculationServiceImpl.java
> +        return percent;
Rate зачем логгируем? Рассчитываем percent, его же и возвращаем

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/CalculationServiceImpl.java
> +        }
Супер, теперь избавились от константы в 366 дней

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ScoringValidationServiceImpl.java
> +public class ScoringValidationServiceImpl implements ScoringValidationService{
Отлично реализовал логгирование и описание ошибок в этом сервисе

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationServiceImpl.java
> +            throw new ValidationException("При заполнении отчества следует использовать латинские буквы.");
Отчество -> имя

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationServiceImpl.java
> +            throw new ValidationException("Минимальная длина отчества составляет "
Отчество -> имя

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationServiceImpl.java
> +            throw new ValidationException("При заполнении отчества следует использовать латинские буквы.");
Отчество -> фамилия

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationServiceImpl.java
> +            throw new ValidationException("Минимальная длина отчества составляет "
Отчество -> фамилия

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationServiceImpl.java
> +public class ValidationServiceImpl implements ValidationService {
Отлично реализовал валидацию, описание ошибок и логгирование в данном сервисе!

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ScoringValidationService.java
> +package com.neoflex.CourseProject.service;
Давай вынесем интерфейсы и классы, отвечающие за валидацию (ScoringValidationService, ValidationService), в отдельный пекедж "validation", чтобы отделить сервисы валидации от сервисов с бизнес логикой

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationService.java
> +public interface ValidationService {
Я бы переименовал, чтобы уйти от общего названия с валидацией, и прийти к уточняющему по аналогии с ScoringValidationService. Назови этот сервис PrescoringValidationService и соответственно имплементацию переименуй

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        log.info("requested loanStatementRequestDto: {}", loanStatementRequestDto);
Переделай на русский, как договаривались

2024-12-01 10:28 UTC, fancestyao commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        log.info("creditDto response: {}", scoringServiceImpl.scoring(scoringDataDto));
Переделай на русский, как договаривались

2024-12-04 07:11 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        log.info("requested loanStatementRequestDto: {}", loanStatementRequestDto);
исправлено

2024-12-04 07:11 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        return (result);
исправлено

2024-12-04 07:12 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        log.info("creditDto response: {}", scoringServiceImpl.scoring(scoringDataDto));
исправлено

2024-12-04 07:13 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/controller/CalculatorController.java
> +        return scoringServiceImpl.scoring(scoringDataDto);
исправлено

2024-12-04 07:18 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/ScoringDataDto.java
> +    private LocalDate passportIssueDate;
исправлено

2024-12-04 07:20 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/CalculationServiceImpl.java
> +        int daysInMonth = 0;
исправлено

2024-12-04 07:21 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/CalculationServiceImpl.java
> +        return percent;
исправлено

2024-12-04 07:22 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ScoringValidationService.java
> +package com.neoflex.CourseProject.service;
исправлено

2024-12-04 07:24 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/service/ValidationService.java
> +public interface ValidationService {
исправлено

2024-12-04 07:25 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/LoanOfferDto.java
> +    @Schema(name = "isInsuranceEnabled", example = "true")
исправлено

2024-12-04 07:26 UTC, NikitaDr-ON commented on CourseProject/src/main/java/com/neoflex/CourseProject/dto/PaymentScheduleElementDto.java
> +    private BigDecimal remainingDebt;
исправлено

2024-12-04 07:33 UTC, merged